// Code generated by hertz generator.

package student

import (
	"context"
	"sync"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	student "github.com/yao-zhi-yuan/hertz-student/biz/model/student"
)

var students sync.Map

// Get .
// @router /query [GET]
func Get(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.QueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	if st, ok := students.Load(req.ID); ok {
		c.JSON(consts.StatusOK, st)
		return
	}

	c.JSON(consts.StatusNotFound, nil)
}

// Add .
// @router add-student-info [POST]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req student.Student
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	hlog.Tracef("req: %v", req)
	students.Store(req.ID, &req)

	c.JSON(consts.StatusOK, req)
}
